#if defined _colors_included
	#endinput
#endif

#define _colors_included

#define COLOR_WHITE      0xEAEAEAFF
#define COLOR_BLACK      0x000000FF
#define COLOR_GREY       0xBFC0C2FF
#define COLOR_YELLOW     0xFFF666FF
#define COLOR_GREEN      0x96DC64FF
#define COLOR_LIGHTGREEN 0xA1CC82FF
#define COLOR_BLUE       0x0095ffff
#define COLOR_SKYBLUE    0x87CEEBFF
#define COLOR_PURPLE     0xC2A2DAFF
#define COLOR_RED        0xFF6347FF

#define COLOR_BLUEGREY_200 0xB0BEC5FF
#define COLOR_TEAL_400     0x26A69AFF
#define COLOR_RED_500      0xF44336FF
#define COLOR_BLUE_500     0x2196F3FF

#define COLOR_PLAYER_TAB 0xAAAAAAFF

#define COLOR_ADMIN_ACTION COLOR_RED
#define COLOR_SERVICES     COLOR_SKYBLUE
#define COLOR_REPORT       COLOR_RED

#define COLOR_ACTIONS      COLOR_PURPLE
#define COLOR_PM           COLOR_YELLOW
#define COLOR_SMS          COLOR_YELLOW
#define COLOR_PHONE        COLOR_YELLOW

#define COLOR_FACTION_CHAT COLOR_BLUE_500
#define COLOR_ADMIN_CHAT   COLOR_TEAL_400
#define COLOR_HELPERS_CHAT COLOR_TEAL_400
#define COLOR_OOC_CHAT     COLOR_LIGHTGREEN

#define COLOR_SUCCESS      COLOR_GREEN
#define COLOR_ERROR        COLOR_RED

#define cWHITE      "{EAEAEA}"
#define cBLACK      "{000000}"
#define cGREY       "{BFC0C2}"
#define cYELLOW     "{FFF666}"
#define cGREEN      "{96DC64}"
#define cLIGHTGREEN "{A1CC82}"
#define cBLUE       "{0095ff}"
#define cSKYBLUE    "{87CEEB}"
#define cPURPLE     "{C2A2DA}"
#define cRED        "{FF6347}"

